version: 2

builds:
  - main: ./cmd/mock-server/main.go
    ldflags:
      - -s -w -X github.com/Caik/go-mock-server/internal/config._version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - 386
      - arm
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm
        goarm: 6
      - goos: windows
        goarch: arm
        goarm: 7

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - src: web/build/client/**
        dst: ui
        strip_parent: true

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"