version: '3.5'
services:
  mock-server:
    build:
      context: .
    image: caik/go-mock-server:latest
    container_name: mock-server
    networks:
      - go-mock-server
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      - ./sample-mocks/:/mocks
    environment:
      - MOCKS_DIR=/mocks
      - UI_DIR=/app/ui

networks:
  go-mock-server: null
